#!/bin/bash
# Run the following command in the root of your project to install this pre-commit hook:
# cp git-hooks/pre-commit .git/hooks/pre-commit; chmod 700 .git/hooks/pre-commit

SINGLE="cmake --preset=dev && cmake --build --preset=dev -t make_single_header && ./build/dev/tools/make_single_header ./include/libfork.hpp ./single_header/libfork.hpp"

eval $SINGLE

if [ $? -ne 0 ]; then
    echo "$SINGLE failed!"
    exit 1
fi

git add ./single_header/libfork.hpp 

exit 0