#!/bin/bash
# Run the following command in the root of your project to install this pre-push hook:
# cp git-hooks/pre-push .git/hooks/pre-push; chmod 700 .git/hooks/pre-push

# Check if we actually have commits to push
commits=`git log @{u}..`
if [ -z "$commits" ]; then
    exit 0
fi

LINT="cmake --preset=dev && cmake --build --preset=dev -t spell-check format-check"

eval $LINT

if [ $? -ne 0 ]; then
    echo "failed $LINT"
    exit 1
fi

LINT="cmake --build --preset=dev && ctest --preset=dev"

eval $LINT

if [ $? -ne 0 ]; then
    echo "failed $LINT"
    exit 1
fi

exit 0