#!/bin/bash
# Run the following command in the root of your project to install this pre-push hook:
# cp git-hooks/pre-push .git/hooks/pre-push; chmod 700 .git/hooks/pre-push

# Check if we actually have commits to push
commits=`git log @{u}..`
if [ -z "$commits" ]; then
    exit 0
fi

# Check there are no untracked changes

pattern=$(git config --get hooks.prepush.sourcepattern)
if [ -z "$pattern" ]; then
    pattern="(?:(?:^|/)CMakeLists\.txt|\.h|\.cpp|\.cmake)$"
fi
    
files=$(git status -u --porcelain --no-column | sed "s/^?? //" | grep -P "$pattern")
if [ -z "$files" ]; then
    exit 0
fi
    
echo
echo "ERROR: Preventing push with untracked source files:"
echo
echo "$files" | sed "s/^/    /"
echo
echo "Either include these files in your commits, add them to .gitignore"
echo "or stash them with git stash -u."
echo


LINT="cmake --preset=dev && cmake --build --preset=dev -t spell-check format-check"

eval $LINT

if [ $? -ne 0 ]; then
    echo "Lint: $LINT failed!"
    exit 1
fi

TEST="cmake --build --preset=dev && ctest --preset=dev"

eval $TEST

if [ $? -ne 0 ]; then
    echo "Test: $TEST failed!"
    exit 1
fi

exit 0